flairs = {
'AFGH': 'Afghanistan',
'AALA': 'Aland Islands',
'ALBA': 'Albania',
'ALGE': 'Algeria',
'ASAM': 'American Samoa',
'ANDO': 'Andorra',
'ANGO': 'Angola',
'ANGU': 'Anguilla',
'ANTA': 'Antarctica',
'ANTI': 'Antigua and Barbuda',
'ARGE': 'Argentina',
'ARME': 'Armenia',
'ARUB': 'Aruba',
'AUST': 'Australia',
'ASTR': 'Austria',
'AZER': 'Azerbaijan',
'BAHA': 'Bahamas',
'BAHR': 'Bahrain',
'BANG': 'Bangladesh',
'BARB': 'Barbados',
'BELA': 'Belarus',
'BELG': 'Belgium',
'BELI': 'Belize',
'BENI': 'Benin',
'BERM': 'Bermuda',
'BHUT': 'Bhutan',
'BOLI': 'Bolivia',
'BOSN': 'Bosnia and Heregovina',
'BOTS': 'Botswana',
'BRAZ': 'Brazil',
'BIOT': 'British Indian Ocean Territory',
'UKVI': 'British Virgin Islands',
'BRUN': 'Brunei',
'BULG': 'Bulgaria',
'BURK': 'Burkina Faso',
'BURU': 'Burundi',
'CAMB': 'Cambodia',
'CAME': 'Cameroon',
'CANA': 'Canada',
'CPVD': 'Cape Verde',
'CAYM': 'Cayman Islands',
'CAFR': 'Central African Republic',
'CHAD': 'Chad',
'CHIL': 'Chile',
'CHIN': 'China',
'CHIS': 'Christmas Island',
'COCO': 'Cocos (Keeling) Islands',
'COLO': 'Colombia',
'COMO': 'Comoros',
'CGDR': 'Democratic Republic of Congo',
'CONG': 'Republic of Congo',
'COOK': 'Cook Islands',
'COST': 'Costa Rica',
'CDIV': 'Cote d Ivoire',
'CROA': 'Croatia',
'CUBA': 'Cuba',
'CURA': 'Curacao',
'CYPR': 'Cyprus',
'CZEC': 'Czech Republic',
'DENK': 'Denmark',
'DJIB': 'Djibouti',
'DMRP': 'Dominican Republic',
'DOMI': 'Dominica',
'ECUA': 'Ecuador',
'EGYP': 'Egypt',
'ELSV': 'El Salvador',
'EQGU': 'Equatorial Guinea',
'ERIT': 'Eritrea',
'ESTO': 'Estonia',
'ETHI': 'Ethiopia',
'FALK': 'Falkland Islands',
'FARO': 'Faroe Islands',
'FIJI': 'Fiji',
'FINL': 'Finland',
'FRAN': 'France',
'FRGU': 'French Guiana',
'FRPL': 'French Polynesia',
'FRST': 'French Southern Territories',
'GABO': 'Gabon',
'GAMB': 'Gambia',
'GEOR': 'Georgia',
'GERM': 'Germany',
'GHAN': 'Ghana',
'GIBR': 'Gibraltar',
'GREE': 'Greece',
'GNLD': 'Greenland',
'GREN': 'Grenada',
'GUAD': 'Guadeloupe',
'GUAM': 'Guam',
'GUAT': 'Guatemala',
'GUER': 'Guernsey',
'GUIN': 'Guinea',
'GUBI': 'Guinea-Bissau',
'GUYA': 'Guyana',
'HAIT': 'Haiti',
'HOND': 'Honduras',
'HGKG': 'Hong Kong',
'HUNG': 'Hungary',
'ICEL': 'Iceland',
'INDI': 'India',
'INDO': 'Indonesia',
'IRAN': 'Iran',
'IRAQ': 'Iraq',
'IREL': 'Ireland',
'ISOM': 'Isle of Man',
'ISRA': 'Israel',
'ITAL': 'Italy',
'JAMA': 'Jamaica',
'JAPA': 'Japan',
'JERS': 'Jersey',
'JORD': 'Jordan',
'KAZA': 'Kazakhstan',
'KENY': 'Kenya',
'KIRI': 'Kiribati',
'NKOR': 'North Korea',
'SKOR': 'South Korea',
'KUWA': 'Kuwait',
'KYRG': 'Kyrgyzstan',
'LAOS': 'Laos',
'LATV': 'Latvia',
'LEBA': 'Lebanon',
'LESO': 'Lesotho',
'LIBE': 'Liberia',
'LIBY': 'Libya',
'LIEC': 'Liechtenstein',
'LITH': 'Lithuania',
'LUXE': 'Luxembourg',
'MACA': 'Macau',
'MACE': 'Macedonia',
'MADA': 'Madagascar',
'MALA': 'Malawi',
'MALY': 'Malaysia',
'MALD': 'Maldives',
'MALI': 'Mali',
'MALT': 'Malta',
'MARS': 'Marshall Islands',
'MART': 'Martinique',
'MAUR': 'Mauritania',
'MATS': 'Mauritius',
'MAYO': 'Mayotte',
'MEXI': 'Mexico',
'MICR': 'Micronesia',
'MOLD': 'Moldova',
'MONA': 'Monaco',
'MONG': 'Mongolia',
'MONT': 'Montenegro',
'MTST': 'Montserrat',
'MORO': 'Morocco',
'MOZA': 'Mozambique',
'MYAN': 'Myanmar',
'NAMB': 'Namibia',
'NAUR': 'Nauru',
'NEPA': 'Nepal',
'NETH': 'Netherlands',
'NWCA': 'New Caledonia',
'NEWZ': 'New Zealand',
'NICA': 'Nicaragua',
'NIGE': 'Niger',
'NGRA': 'Nigeria',
'NIUE': 'Niue',
'NFIS': 'Norfolk Island',
'NMIS': 'Northern Mariana Islands',
'NORW': 'Norway',
'OMAN': 'Oman',
'PAKI': 'Pakistan',
'PALA': 'Palau',
'PALE': 'Palestine',
'PANA': 'Panama',
'PPNG': 'Papua New Guiea',
'PARA': 'Paraguay',
'PERU': 'Peru',
'PHIL': 'Philippines',
'PITC': 'Pitcairn Islands',
'POLA': 'Poland',
'PORL': 'Portugal',
'PUER': 'Puerto Rico',
'QATA': 'Qatar',
'ROMA': 'Romania',
'RUSS': 'Russia',
'RWAN': 'Rwanda',
'SHAT': 'Saint Helena, Ascension and Tristan da Cunha',
'SKAN': 'Saint Kitts and Nevis',
'STLU': 'Saint Lucia',
'SPAM': 'Saint Pierre and Miquelon',
'SVAG': 'Saint Vincent and the Grenadines',
'SAMO': 'Samoa',
'SNMN': 'San Marino',
'STAP': 'Sao Tome and Principe',
'SAUD': 'Saudi Arabia',
'SCHA': 'Schlangen',
'SENE': 'Senegal',
'SERB': 'Serbia',
'SEYC': 'Seychelles',
'SILE': 'Sierra Leone',
'SING': 'Singapore',
'STMA': 'Sint Maarten',
'SVAK': 'Slovakia',
'SLOV': 'Slovenia',
'SOLO': 'Solomon Islands',
'SOMA': 'Somalia',
'SOAF': 'South Africa',
'SGSS': 'South Georgia and the South Sandwich Islands',
'SSUD': 'South Sudan',
'ESPA': 'Spain',
'SRIL': 'Sri Lanka',
'SUDA': 'Sudan',
'SURI': 'Suriname',
'SWAZ': 'Swaziland' ,
'SWED': 'Sweden',
'SWIT': 'Switzerland',
'SYRI': 'Syria',
'TAIW': 'Taiwan',
'TAJI': 'Tajikistan',
'TANZ': 'Tanzania',
'THAI': 'Thailand',
'TILE': 'Timor-Leste',
'TKMS': 'Turkmenistan',
'TOKE': 'Tokelau',
'TOGO': 'Togo',
'TONG': 'Tonga',
'TRIN': 'Trinidad and Tobago',
'TUNI': 'Tunisia',
'TURK': 'Turkey',
'TACI': 'Turks and Caicos Islands',
'TUVA': 'Tuvalu',
'UKRA': 'Ukraine',
'UGAN': 'Uganda',
'UNAE': 'United Arab Emirates',
'UKGB': 'United Kingdom',
'UNSA': 'United States of America',
'USVI': 'United States Virgin Islands',
'URUG': 'Uruguay',
'UZBE': 'Uzbekistan',
'VANA': 'Vanuatu',
'HOLY': 'Vatican City',
'VENE': 'Venezuela',
'VIET': 'Vietnam',
'WAFU': 'Wallis and Futuna',
'WTSA': 'Western Sahara',
'YEME': 'Yemen',
'ZAMB': 'Zambia',
'ZIMB': 'Zimbabwe',
'UNIN': 'United Nations',
'AFRI': 'African Union',
'ARAB': 'Arab League',
'ASEA': 'ASEAN',
'CMIS': 'Commonwealth of Independent States',
'COMW': 'Commonwealth of Nations',
'EURO': 'European Union',
'FRCO': 'La Francophonie',
'NATO': 'NATO',
'NRDC': 'Nordic Council',
'OLYM': 'Olympics',
'ORIC': 'Organisation of Islamic Cooperation',
'RDCT': 'Red Crescent',
'RDCS': 'Red Cross',
'RDCY': 'Red Crystal',
'ABKH': 'Abkhazia',
'KOSO': 'Kosovo',
'NGKB': 'Nagorno-Karabakh',
'NCYP': 'Northern Cyprus',
'SOML': 'Somaliland',
'SOSS': 'South Ossetia',
'TRNS': 'Transnistria',
'SEAL': 'Principality of Sealand',
'ALBR': 'Alberta',
'BRCO': 'British Columbia',
'MANI': 'Manitoba',
'NEBR': 'New Brunswick',
'NELA': 'Newfoundland and Labrador',
'NWTR': 'Northwest Territories',
'NOVA': 'Nova Scotia',
'NUNA': 'Nunavut',
'ONTA': 'Ontario',
'PREI': 'Prince Edward Island',
'QUEB': 'Quebec',
'SASK': 'Sakatchewan',
'YUKO': 'Yukon',
'ALAB': 'Alabama',
'ALAS': 'Alaska',
'ARIZ': 'Arizona',
'ARKA': 'Arkansas',
'CALI': 'California',
'COLR': 'Colorado',
'CONN': 'Connecticut',
'DELA': 'Delaware',
'FLOR': 'Florida',
'GERG': 'Georgia',
'HAWA': 'Hawaii',
'IDAH': 'Idaho',
'ILLI': 'Illinois',
'INNA': 'Indiana',
'IOWA': 'Iowa',
'KANS': 'Kansas',
'KNTC': 'Kentucky',
'LOUI': 'Louisiana',
'MAIN': 'Maine',
'MARY': 'Maryland',
'MASS': 'Massachusetts',
'MICH': 'Michigan',
'MINN': 'Minnesota',
'MSSP': 'Mississippi',
'MISS': 'Missouri',
'MNTA': 'Montana',
'NEBA': 'Nebraska',
'NEVA': 'Nevada',
'NEWH': 'New Hampshire',
'NEWJ': 'New Jersey',
'NMEX': 'New Mexico',
'NEWY': 'New York',
'NCAR': 'North Carolina',
'NDAK': 'North Dakota',
'OHIO': 'Ohio',
'OKLA': 'Oklahoma',
'OREG': 'Oregon',
'PENN': 'Pennsylvania',
'RHOD': 'Rhode Island',
'SCAR': 'South Carolina',
'SDAK': 'South Dakota',
'TENN': 'Tennessee',
'TEXA': 'Texas',
'UTAH': 'Utah',
'VERM': 'Vermont',
'VIRG': 'Virginia',
'WSHN': 'Washington',
'WASH': 'Washington D.C.',
'WVIR': 'West Virginia',
'WISC': 'Wisconsin',
'WYOM': 'Wyoming',
'AICH': 'Aichi',
'AKIT': 'Akita',
'AOMO': 'Aomori',
'CHIB': 'Chiba',
'EHIM': 'Ehime',
'FUKI': 'Fukui',
'FUKO': 'Fukuoka',
'FUKS': 'Fukushima',
'GIFU': 'Gifu',
'GNMA': 'Gunma',
'HIRO': 'Hiroshima',
'HOKK': 'Hokkaido',
'HYGO': 'Hyogo',
'IBAR': 'Ibaraki',
'ISHI': 'Ishikawa',
'IWAT': 'Iwate',
'KAGA': 'Kagawa',
'KAGO': 'Kagoshima',
'KARA': 'Karafuto',
'KANA': 'Kanagawa',
'KCHI': 'Kochi',
'KUMA': 'Kumamoto',
'KYTO': 'Kyoto',
'MIEE': 'Mie',
'MIYA': 'Miyagi',
'MIYZ': 'Miyazaki',
'NAGN': 'Nagano',
'NAGS': 'Nagasaki',
'NARA': 'Nara',
'NIGT': 'Niigata',
'OITA': 'Oita',
'OKAY': 'Okayama',
'OKIN': 'Okinawa',
'OSAK': 'Osaka',
'SAGA': 'Saga',
'SAIT': 'Saitama',
'SHIG': 'Shiga',
'SHIM': 'Shimane',
'SHIZ': 'Shizuoka',
'TOCH': 'Tochigi',
'TOKU': 'Tokushima',
'TOKY': 'Tokyo',
'TOTT': 'Tottori',
'TOYA': 'Toyama',
'WAKA': 'Wakayama',
'YMGT': 'Yamagata',
'YMGU': 'Yamaguchi',
'YMNA': 'Yamanashi',
'BADE': 'Baden-Wurttemberg',
'BAVA': 'Bavaria',
'BERL': 'Berlin',
'BRAN': 'Brandenburg',
'BREM': 'Bremen',
'HAMB': 'Hamburg',
'HESS': 'Hesse',
'LSAX': 'Lower Saxony',
'MEVO': 'Mecklenburg-Vorpommern',
'NRHW': 'North Rhine-Westphalia',
'RHPA': 'Rhineland-Palatinate',
'SAAR': 'Saarland',
'SAXO': 'Saxony',
'SAXA': 'Saxony-Anhalt',
'SCHL': 'Schleswig-Holstein',
'THUR': 'Thuringia',
'ANDA': 'Andalusia',
'ARAG': 'Aragon',
'ASTU': 'Asturias',
'BALE': 'Balearic Islands',
'BASQ': 'Basque Country',
'CATA': 'Catalonia',
'CNRY': 'Canary Islands',
'CANT': 'Cantabria',
'CSLE': 'Castile and Leon',
'CSLM': 'Castile-La Mancha',
'CEUT': 'Ceuta',
'EXTR': 'Extremadura',
'GALI': 'Galicia',
'MADR': 'Madrid',
'MELI': 'Melilla',
'MURC': 'Murcia',
'NAVR': 'Navarre',
'RIOJ': 'La Rioja',
'VALE': 'Valencia',
'BRUS': 'Brussels',
'FLAN': 'Flanders',
'GEBE': 'German-Speaking Community of Belgium',
'WALL': 'Wallonia',
'ENGL': 'England',
'SCOT': 'Scotland',
'WALE': 'Wales',
'CONC': 'Connacht',
'LEIN': 'Leinster',
'MUNS': 'Munster',
'ULSE': 'Ulster',
'BONA': 'Bonaire',
'DREN': 'Drenthe',
'FLEV': 'Flevoland',
'FRIE': 'Friesland',
'GELD': 'Gelderland',
'GRON': 'Groningen',
'LIMB': 'Limburg',
'NBRA': 'North Brabant',
'NHOL': 'North Holland',
'OVIJ': 'Overijssel',
'SABA': 'Saba',
'STEU': 'Sint Eustatius',
'SHOL': 'South Holland',
'UTRE': 'Utrecht',
'ZEEL': 'Zeeland',
'JOHO': 'Johor',
'KEDA': 'Kedah',
'KELA': 'Kelantan',
'MALC': 'Malacca',
'NEGE': 'Negeri Sembilan',
'PAHA': 'Pahang',
'PENA': 'Penang',
'PERA': 'Perak',
'PERL': 'Perlis',
'SABH': 'Sabah',
'SAWK': 'Sarawak',
'SELA': 'Selangor',
'TNGG': 'Terengganu',
'ADYG': 'Adygea',
'ALTA': 'Altai',
'BASH': 'Bashkortostan',
'BURY': 'Buryatia',
'CHEC': 'Chechnya',
'CHUK': 'Chukotka',
'CHUV': 'Chuvashia',
'DAGE': 'Dagestan',
'INGU': 'Ingushetia',
'KABA': 'Kabardino-Balkaria',
'KALM': 'Kalmykia',
'KARA': 'Karachay-Cherkessia',
'KARE': 'Karelia',
'KHAK': 'Khakassia',
'KHAN': 'Khanty-Mansi',
'KOMI': 'Komi',
'MARI': 'Mari El',
'MORD': 'Mordovia',
'NENE': 'Nenetsia',
'NOSS': 'North Ossetia-Alania',
'SAKH': 'Sakha',
'TATA': 'Tatarstan',
'TYVA': 'Tuva',
'UDMU': 'Udmurtia',
'YAMA': 'Yamalo-Nenets',
'ACRE': 'Acre',
'ALAG': 'Alagoas',
'AMAP': 'Amapa',
'AMAZ': 'Amazonas',
'BAHI': 'Bahia',
'BRAS': 'Brasilia',
'CEAR': 'Ceara',
'ESPI': 'Espirito Santo',
'GOIA': 'Goias',
'MARA': 'Maranhao',
'MATO': 'Mato Grosso',
'MGDS': 'Mato Grosso do Sul',
'MINA': 'Minas Gerais',
'PARB': 'Para',
'PRAB': 'Paraiba',
'PRAN': 'Parana',
'PERN': 'Pernambuco',
'PIAU': 'Piaui',
'RDJS': 'Rio de Janeiro',
'RGDN': 'Rio Grande do Norte',
'RGDS': 'Rio Grande do Sul',
'ROND': 'Rondonia',
'RORA': 'Roraima',
'SANC': 'Santa Catarina',
'SPAS': 'Sao Paulo State',
'SERG': 'Sergipe',
'TOCA': 'Tocantins',
'ANJO': 'Anjouan',
'GRCO': 'Grande Comore',
'MOHE': 'Moheli',
'ANKO': 'Ankole',
'BUGA': 'Buganda',
'BUNY': 'Bunyoro',
'BUSO': 'Busoga',
'TORU': 'Toro',
'AFAR': 'Afar',
'AMHA': 'Amhara',
'BEGU': 'Benishangul-Gumuz',
'GAME': 'Gambela',
'HARA': 'Harari',
'OROM': 'Oromia',
'SNNP': 'SNNPR',
'SOMR': 'Somali Region',
'TIGR': 'Tigray',
'RSSR': 'Russian SFSR',
'UKSR': 'Ukrainian SSR',
'BYSR': 'Byelorussian SSR',
'UZSR': 'Uzbek SSR',
'KZSR': 'Kazakh SSR',
'GGSR': 'Georgian SSR',
'AZSR': 'Azerbaijan SSR',
'LTSR': 'Lithuanian SSR',
'MLSR': 'Moldavian SSR',
'LTSR': 'Latvian SSR',
'KRSR': 'Kirghiz SSR',
'TJSR': 'Tajik SSR',
'ARSR': 'Armenian SSR',
'TKSR': 'Turkmen SSR',
'ESSR': 'Estonian SSR',
'ABOR': 'Aboriginal Australians',
'ADJA': 'Adjara',
'AFG2': 'Afghanistan (1919)',
'AFG3': 'Afghanistan (1974)',
'AFG4': 'Afghanistan (1992)',
'ALAW': 'Alawite State',
'ALBU': 'Albuquerque',
'ALDE': 'Alderney',
'ALEX': 'Alexandria',
'AMST': 'Amsterdam',
'BKFG': 'Anarchism',
'ANCH': 'Anchorage',
'ANG2': 'Anguilla (1967)',
'ANJ2': 'Anjouan (1997)',
'ASHA': 'Ashanti',
'ASSY': 'Assyria',
'ANTL': 'Atlanta',
'AUS2': 'Australia (Federation Flag)',
'AST2': 'Austria (1804)',
'AUHU': 'Austria-Hungary',
'AZAD': 'Azad Kashmir',
'BALT': 'Baltimore',
'BARO': 'Barotseland',
'BEL2': 'Belarus (1991)',
'BEN2': 'Benin (1975)',
'BERB': 'Berber',
'BIAF': 'Biafra',
'BIRM': 'Birmingham',
'BLCO': 'Black Country',
'BOGO': 'Bogota',
'WIPH': 'Bolivia (Wiphala)',
'BOPH': 'Bophuthatswana',
'BOS2': 'Bosnia (1878)',
'BOS3': 'Bosnia and Herzegovina (1992)',
'BOST': 'Boston',
'BRA2': 'Brazil (1822)',
'BRA3': 'Brazil (1889)',
'BRAT': 'British Antarctic Territory',
'BRTT': 'Brittany',
'BUDD': 'Buddhist',
'BUFF': 'Buffalo',
'BURM': 'Burma (1948)',
'CABI': 'Cabinda',
'CAIR': 'Cairo',
'CALG': 'Calgary',
'CAN2': 'Canada (1921)',
'CAPE': 'Cape Town',
'CPV2': 'Cape Verde (1975)',
'CART': 'Cartagena',
'CASA': 'Casamance',
'CASC': 'Cascadia',
'CEAM': 'Central America',
'CEYL': 'Ceylon (1948)',
'CHAG': 'Chagossians',
'CHAR': 'Charlotte',
'CHER': 'Cherokee',
'CHIC': 'Chicago',
'CHL2': 'Chile (1812)',
'CHI2': 'China (1890)',
'CHI3': 'China (1912)',
'CHRI': 'Christian',
'CINC': 'Cincinnati',
'CISK': 'Ciskei',
'CLEV': 'Cleveland',
'CON2': 'Congo-Brazzaville (1970)',
'COFS': 'Congo Free State',
'COO2': 'Cook Islands (1973)',
'CSAB': 'Confederate States of America Battle Flag (1861)',
'COPT': 'Coptic',
'CORS': 'Corsica',
'COS2': 'Costa Rica (1840)',
'CRET': 'Crete',
'CRIM': 'Crimea',
'CUB2': 'Cuba (1868)',
'CYRE': 'Cyrenaica',
'DALL': 'Dallas',
'DANZ': 'Danzig',
'DENV': 'Denver',
'DETR': 'Detroit',
'DRUZ': 'Druze',
'DUBA': 'Dubai',
'EANG': 'East Anglia',
'ETUR': 'East Turkestan',
'EAIS': 'Easter Island',
'ECU2': 'Ecuador (1845)',
'EDMO': 'Edmonton',
'EGY2': 'Egypt (1923)',
'ELS2': 'El Salvador (1877)',
'ERI2': 'Eritrea (1952)',
'ETH2': 'Ethiopia (1897)',
'EWEN': 'Ewe',
'FMYS': 'Federated Malay States',
'FIJ2': 'Fiji (1871)',
'FIUM': 'Fiume',
'FLRN': 'Florence',
'FRA2': 'France (1814)',
'GAGA': 'Gagauzia',
'GEO2': 'Georgia (1990)',
'GER2': 'Germany (1871)',
'EGER': 'East Germany',
'GCOL': 'Gran Colombia',
'GBR2': 'Great Britain (1606)',
'GRE2': 'Greece (1822)',
'GUA2': 'Guatemala (1858)',
'DENH': 'The Hague',
'HAID': 'Haida',
'HAI2': 'Haiti (1964)',
'HALI': 'Halifax',
'HAMI': 'Hamilton',
'HEJA': 'Hejaz',
'HREM': 'Holy Roman Empire',
'HONO': 'Honolulu',
'IRUS': 'Imperial Russia',
'INDP': 'Indianapolis',
'IRN2': 'Iran (1964)',
'IRQ2': 'Iraq (1924)',
'IRQ3': 'Iraq (1959)',
'IRE2': 'Ireland (Harp Flag)',
'IROQ': 'Iroquois',
'ITA2': 'Italy (1861)',
'JACK': 'Jacksonville',
'JAIN': 'Jain',
'JKAS': 'Jammu and Kashmir',
'JEBE': 'Jebel Shammar',
'JOBU': 'Johannesburg',
'JUBA': 'Jubaland',
'DKAM': 'Democratic Kampuchea',
'KANO': 'Kano',
'KANC': 'Kansas City',
'KARK': 'Karakalpakstan',
'KRNK': 'Karnataka',
'KATA': 'Katanga',
'KEYW': 'Key West',
'KHME': 'Khmer Republic',
'KINS': 'Kinshasa',
'KRAK': 'Krakow',
'KUAL': 'Kuala Lumpur',
'KUBA': 'Kuban',
'KURD': 'Kurdistan',
'LABR': 'Labrador',
'LADK': 'Ladakh',
'LAO2': 'Laos (1952)',
'LASV': 'Las Vegas',
'LEMK': 'Lemko Republic',
'LES3': 'Lesotho (1966)',
'LES2': 'Lesotho (1987)',
'LIB2': 'Libya (1977)',
'LOSA': 'Los Angeles',
'LOUV': 'Louisville',
'LUX2': 'Luxembourg (Red Lion)',
'MAAS': 'Maasai',
'MAC2': 'Macedonia (1992)',
'MACG': 'Macedonia, Greece',
'MLW2': 'Malawi (2010)',
'MFED': 'Mali Federation',
'MAL2': 'Malta (Civil Ensign)',
'MNCH': 'Manchukuo',
'MAOR': 'Maori',
'MAPU': 'Mapuche',
'MAYA': 'Maya',
'MEMP': 'Memphis',
'MENG': 'Mengjiang',
'METI': 'Metis',
'MIAM': 'Miami',
'MILW': 'Milwaukee',
'MOH2': 'Moheli (1997)',
'MNG2': 'Mongolia (1924)',
'MON2': 'Montenegro (1993)',
'MTRL': 'Montreal',
'MORM': 'Mormon',
'MOSC': 'Moscow',
'MOZ2': 'Mozambique (1975)',
'NAIR': 'Nairobi',
'NAVJ': 'Navajo',
'NEJD': 'Nejd',
'NET2': 'Netherlands (Prince Flag)',
'NANT': 'Netherlands Antilles',
'NEVI': 'Nevis',
'NENG': 'New England',
'NGR2': 'New Grenada (1834)',
'NORL': 'New Orleans',
'NEYC': 'New York City',
'NZL2': 'New Zealand (Silver Fern)',
'NFLD': 'Newfoundland',
'NIC2': 'Nicaragua (1854)',
'NORN': 'Northern Ireland (1953)',
'NVDC': 'North Vancouver (District)',
'OCCI': 'Occitania',
'OGON': 'Ogoni',
'ORFS': 'Orange Free State',
'ORKN': 'Orkney',
'OSLO': 'Oslo',
'OTTA': 'Ottawa',
'PAFR': 'Pan-African',
'PNG2': 'Papua New Guinea (1970)',
'PAR2': 'Paraguay (1826)',
'PARI': 'Paris',
'PEBO': 'Peru-Bolivia',
'PHLD': 'Philadelphia',
'PHOE': 'Phoenix',
'PITT': 'Pittsburgh',
'PODG': 'Podgorica',
'PORT': 'Portland',
'POR2': 'Portugal (1830)',
'PRAG': 'Prague',
'PRUS': 'Prussia',
'PUNT': 'Puntland',
'QBCY': 'Quebec City',
'REGI': 'Regina',
'RHDE': 'Rhodesia',
'RIFR': 'Rif Republic',
'RIDJ': 'Rio de Janeiro (city)',
'RIOG': 'Rio Grande Republic',
'ROMI': 'Roma',
'ROME': 'Rome',
'ROTT': 'Rotterdam',
'RUS2': 'Russia (1858)',
'RWA2': 'Rwanda (1962)',
'RWEN': 'Rwenzururu',
'SAA2': 'Saar (1945)',
'SAMI': 'Sami People',
'SCNA': 'Saint Christopher-Nevis-Anguilla',
'SALC': 'Salt Lake City',
'SAND': 'San Diego',
'SANF': 'San Francisco',
'SAOP': 'Sao Paulo (city)',
'SARK': 'Sark',
'SATN': 'Satanism',
'SARD': 'Sardinia',
'SEAT': 'Seattle',
'SEN2': 'Senegal (1958)',
'SEPT': 'Septinsular Republic',
'SEY3': 'Seychelles (1976)',
'SEY2': 'Seychelles (1977)',
'SHET': 'Shetland',
'SICI': 'Sicily',
'SIKH': 'Sikh',
'SIKK': 'Sikkim',
'SAF2': 'South Africa (1928)',
'SKAS': 'South Kasai',
'SMOL': 'South Moluccas',
'SPER': 'South Peru',
'USSR': 'Soviet Union',
'SPA2': 'Spain (1931)',
'SMOR': 'Spanish Morocco',
'STLO': 'St. Louis',
'SUD2': 'Sudan (1956)',
'SULU': 'Sulu',
'SUVA': 'Suvadives',
'SWNO': 'Sweden-Norway',
'SYR2': 'Syria (1920)',
'SYRA': 'Syria (Opposition)',
'SZEK': 'Szekely',
'TANG': 'Tanganyika',
'TAIZ': 'Tangier International Zone',
'TANU': 'Tannu Tuva',
'THI2': 'Thailand (1855)',
'TIBE': 'Tibet',
'TOKY': 'Tokyo',
'TOG2': 'Togo (1958)',
'TORO': 'Toronto',
'TORR': 'Torres Strait Islanders',
'TRCA': 'Transcaucasia',
'TRKE': 'Transkei',
'TRVL': 'Transvaal',
'TRSV': 'Transylvania',
'TRIP': 'Tripolitania',
'TTPI': 'Trust Territory of the Pacific Islands',
'TUV2': 'Tuvalu (1996)',
'UGA2': 'Uganda (1962)',
'USA2': 'United States (1776)',
'USA3': 'United States (Grand Union)',
'UPVO': 'Upper Volta',
'URUA': 'Uruguay (Artigas)',
'URUT': 'Uruguay (Treinta y Tres)',
'VANC': 'Vancouver',
'VEND': 'Venda',
'VER2': 'Vermont Republic',
'VICT': 'Victoria, BC, Canada',
'SVE1': 'South Vietnam (1954)',
'SVE2': 'South Vietnam (1975)',
'VOJV': 'Vojvodina',
'WESS': 'Wessex',
'WIFD': 'West Indies Federation',
'WFLO': 'West Florida',
'WPAP': 'West Papua Independence',
'WINP': 'Winnipeg',
'NYE1': 'North Yemen (1927)',
'NYE2': 'North Yemen (1962)',
'SYEM': 'South Yemen',
'YUCA': 'Yucatan',
'YUGO': 'Yugoslavia (1992)',
'SFRY': 'Yugoslavia (1946)',
'ZAIR': 'Zaire',
'ZANZ': 'Zanzibar',
'ZAN2': 'Zanzibar (1963)',
'ZIRH': 'Zimbabwe-Rhodesia'
}
